 require_relative '../node_modules/react-native/scripts/react_native_pods'
 require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

 platform :ios, '12.0'

 target 'BlueBillywigPlayerExample' do
   config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

   use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

   # Enables Flipper.
   #
   # Note that if you have use_frameworks! enabled, Flipper will not work and
   # you should disable these next few lines.
     use_flipper!({ 'Flipper' => '0.162.0' })

   post_install do |installer|
      react_native_post_install(installer)
      __apply_Xcode_12_5_M1_post_install_workaround(installer)

     installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
	       config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
         config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
         config.build_settings['ENABLE_BITCODE'] = 'YES'
         config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
       end
     end
     flipper_post_install(installer)
   end
 end